import type { Locale } from './markets';

const copy = {
  fr: {
    passport: 'PASSEPORT DE COMPÉTENCES', welcome: 'Bienvenue.', firstName: 'Votre prénom', country: 'Pays de résidence', create: 'Continuer', creating: 'Création…', locked: 'Passeport verrouillé.', unlock: 'Déverrouiller', protected: 'Votre identité et vos compétences restent protégées sur cet appareil.', preparing: 'Préparation de votre passeport…', protectedPassport: 'PASSEPORT PROTÉGÉ', welcomeCopy: 'Créez un passeport local, privé et prêt à évoluer avec vous.',
    skillNew: 'Nouvelle compétence', skillIntro: 'Ajoutez une compétence. Elle sera déclarée au niveau débutant et pourra évoluer avec votre tuteur.', skillExample: 'Ex. Prise de parole', addSkill: 'Ajouter au passeport', skillAdded: 'Compétence ajoutée', skillAddedCopy: 'Elle apparaît maintenant dans votre passeport.', skills: '{{count}} compétence{{plural}}', skillReady: 'Votre passeport est prêt.', skillReadyCopy: 'Ajoutez votre première compétence pour commencer un échange.', searchSkill: 'Rechercher une compétence', noSkill: 'Aucune compétence trouvée.', updated: 'Mis à jour le {{date}}', level: 'Niveau {{level}} sur 4', visible: 'Visible', hidden: 'Masquée', showSkill: 'Afficher {{name}}', hideSkill: 'Masquer {{name}}', deleteSkill: 'Supprimer {{name}}', deleteSkillTitle: 'Supprimer cette compétence ?', deleteSkillCopy: '{{name}} sera retirée de ce passeport.', skillShown: 'Compétence affichée', skillHidden: 'Compétence masquée', skillDeleted: 'Compétence supprimée',
    wallet: 'Crédits restants', credits: '{{amount}} crédit{{plural}}', viewCredits: 'Voir mes crédits restants', creditInfo: '10 crédits sont offerts à la création. 1 crédit = 100 FCFA = 60 secondes de tuteur vocal. Une réponse texte coûte 0,25 crédit.', recharge: 'Recharger des crédits', paymentPending: 'Paiement en préparation', paymentPendingCopy: 'Vous recevrez une confirmation après validation du paiement.', rechargeUnavailable: 'Recharge indisponible', testCredit: 'Ajouter 500 FCFA de test', testCreditAdded: 'Crédit de test ajouté', testCreditAddedCopy: '5 crédits de test ont été ajoutés.', paymentNotice: 'Les crédits sont ajoutés après confirmation signée du paiement. Le checkout Jèko nécessite les identifiants marchands et la validation sandbox.',
    transfer: 'Transférer', transferCopy: 'Votre export est chiffré. Choisissez une phrase secrète longue et ne la partagez pas avec le code.', secret: 'Phrase secrète (12 caractères min.)', export: 'Copier mon export chiffré', exportReady: 'Export prêt', exportReadyCopy: 'Copiez le code affiché pour le conserver.', import: 'Importer ce passeport', exportUnavailable: 'Export impossible', importUnavailable: 'Import impossible', importUnavailableCopy: 'Vérifiez le code et la phrase secrète.', passportImported: 'Passeport importé', passportImportedCopy: 'Vos compétences sont maintenant disponibles sur cet appareil.', downloadSkills: 'Télécharger mes compétences',
    hello: 'Bonjour, {{name}}.', flames: 'Flammes', flameRule: '+1 après 1 min de pratique · −1 par jour manqué', chooseTutor: 'Choisissez votre tuteur', startConversation: 'Démarrer la conversation', openProfile: 'Ouvrir mon profil',
    tutorFallback: 'Tuteur', skillFallback: 'Compétence', you: 'VOUS', textTutor: 'Passer au tuteur texte', start: 'Démarrer', end: 'Terminer', learningCanvas: 'CANVAS D’APPRENTISSAGE', sharedConversation: 'Texte et voix utilisent la même conversation, centrée sur votre dernier message.', switchVoice: 'Passer au tuteur vocal', writeTo: 'Écrire à {{name}}', send: 'Envoyer le message', stopReply: 'Arrêter la réponse', replyInProgress: 'Réponse en cours, toucher pour arrêter.', assessment: 'Évaluation en 5 questions', assessmentProgress: 'Évaluation : {{question}}/5 · série {{success}}/5', chooseSkill: 'Choisissez une compétence', chooseSkillCopy: 'Sélectionnez la compétence avant de démarrer le tuteur.', assessmentCopy: 'Sélectionnez d’abord la compétence à évaluer.', assessmentStarted: 'Évaluation en 5 questions démarrée.', updateSuccess: 'Mise à jour réussie', tutorUnavailable: 'Tuteur indisponible', retry: 'Réessayez dans un instant.', conversationUnavailable: 'Conversation indisponible', conversationEnded: 'Conversation terminée', creditsUsed: '{{amount}} crédit{{plural}} consommé{{plural}}.', passportUpdated: 'Passeport mis à jour', passportUpdatedCopy: '{{name}} passe au niveau {{level}}.',
    search: 'Rechercher', back: 'Retour', close: 'Fermer', countryPickCopy: 'Choisissez le pays qui vous correspond.',
    history: 'Historique des conversations', conversation: 'Conversation', historyCopy: 'Ces transcriptions sont conservées uniquement sur cet appareil.', noHistory: 'Aucune conversation enregistrée.', messageCount: '{{count}} message{{plural}}', deleteConversation: 'Supprimer cette conversation', deleteConversationTitle: 'Supprimer cette conversation ?', deleteConversationCopy: 'Cette transcription sera effacée uniquement de ce téléphone.', deleteAll: 'Tout supprimer', deleteAllTitle: 'Tout supprimer ?', deleteAllCopy: 'Toutes les transcriptions locales seront effacées. Cette action est irréversible.', cancel: 'Annuler', delete: 'Supprimer',
    profile: 'Mon profil', conversations: 'Mes conversations', billing: 'Facturation', signature: 'Fait avec le ❤️ à Abidjan par Etudesk', saveProfile: 'Enregistrer le profil', saving: 'Enregistrement…', saveHistory: 'Conserver mes conversations', saveHistoryCopy: 'Désactivé par défaut. Si activé, le texte est chiffré et reste uniquement sur ce téléphone.', deletePassport: 'Supprimer le passeport', deleting: 'Suppression…', deletePassportTitle: 'Supprimer le passeport ?', deletePassportCopy: 'Votre profil, vos compétences, crédits et transcriptions seront supprimés. Cette action est irréversible.', deleteUnavailable: 'Suppression impossible', saveUnavailable: 'Impossible à enregistrer', profileSaved: 'Profil enregistré',
    nameRequired: 'Prénom requis', nameRequiredCopy: 'Indiquez le prénom à afficher dans votre passeport.', profileCreated: 'Passeport créé', profileCreatedCopy: 'Votre profil est enregistré uniquement sur cet appareil.', profileError: 'Profil', error: 'Erreur', unavailable: 'Indisponible',
  },
  en: {
    passport: 'SKILLS PASSPORT', welcome: 'Welcome.', firstName: 'Your first name', country: 'Country of residence', create: 'Continue', creating: 'Creating…', locked: 'Passport locked.', unlock: 'Unlock', protected: 'Your identity and skills remain protected on this device.', preparing: 'Preparing your passport…', protectedPassport: 'PROTECTED PASSPORT', welcomeCopy: 'Create a local, private passport that evolves with you.',
    skillNew: 'New skill', skillIntro: 'Add a skill. It will start at beginner level and can evolve with your tutor.', skillExample: 'e.g. Public speaking', addSkill: 'Add to passport', skillAdded: 'Skill added', skillAddedCopy: 'It now appears in your passport.', skills: '{{count}} skill{{plural}}', skillReady: 'Your passport is ready.', skillReadyCopy: 'Add your first skill to start a conversation.', searchSkill: 'Search for a skill', noSkill: 'No skills found.', updated: 'Updated {{date}}', level: 'Level {{level}} of 4', visible: 'Visible', hidden: 'Hidden', showSkill: 'Show {{name}}', hideSkill: 'Hide {{name}}', deleteSkill: 'Delete {{name}}', deleteSkillTitle: 'Delete this skill?', deleteSkillCopy: '{{name}} will be removed from this passport.', skillShown: 'Skill shown', skillHidden: 'Skill hidden', skillDeleted: 'Skill deleted',
    wallet: 'Credits remaining', credits: '{{amount}} credit{{plural}}', viewCredits: 'View my remaining credits', creditInfo: '10 credits are included when you create your account. 1 credit = 100 FCFA = 60 seconds with the voice tutor. A text reply costs 0.25 credit.', recharge: 'Add credits', paymentPending: 'Payment being prepared', paymentPendingCopy: 'You will receive a confirmation after your payment is approved.', rechargeUnavailable: 'Top-up unavailable', testCredit: 'Add 500 FCFA test credit', testCreditAdded: 'Test credit added', testCreditAddedCopy: '5 test credits have been added.', paymentNotice: 'Credits are added after signed payment confirmation. Jèko checkout requires merchant credentials and sandbox approval.',
    transfer: 'Transfer', transferCopy: 'Your export is encrypted. Choose a long secret phrase and never share it with the code.', secret: 'Secret phrase (12 characters min.)', export: 'Copy encrypted export', exportReady: 'Export ready', exportReadyCopy: 'Copy the code shown to keep it safe.', import: 'Import this passport', exportUnavailable: 'Export unavailable', importUnavailable: 'Import unavailable', importUnavailableCopy: 'Check the code and secret phrase.', passportImported: 'Passport imported', passportImportedCopy: 'Your skills are now available on this device.', downloadSkills: 'Download my skills',
    hello: 'Hello, {{name}}.', flames: 'Flames', flameRule: '+1 after 1 minute of practice · −1 for each missed day', chooseTutor: 'Choose your tutor', startConversation: 'Start conversation', openProfile: 'Open my profile',
    tutorFallback: 'Tutor', skillFallback: 'Skill', you: 'YOU', textTutor: 'Switch to text tutor', start: 'Start', end: 'End', learningCanvas: 'LEARNING CANVAS', sharedConversation: 'Text and voice use the same conversation, focused on your latest message.', switchVoice: 'Switch to voice tutor', writeTo: 'Write to {{name}}', send: 'Send message', stopReply: 'Stop reply', replyInProgress: 'Reply in progress, tap to stop.', assessment: '5-question assessment', assessmentProgress: 'Assessment: {{question}}/5 · streak {{success}}/5', chooseSkill: 'Choose a skill', chooseSkillCopy: 'Select a skill before starting the tutor.', assessmentCopy: 'First select the skill to assess.', assessmentStarted: '5-question assessment started.', updateSuccess: 'Update complete', tutorUnavailable: 'Tutor unavailable', retry: 'Try again in a moment.', conversationUnavailable: 'Conversation unavailable', conversationEnded: 'Conversation ended', creditsUsed: '{{amount}} credit{{plural}} used.', passportUpdated: 'Passport updated', passportUpdatedCopy: '{{name}} is now at {{level}} level.',
    search: 'Search', back: 'Back', close: 'Close', countryPickCopy: 'Choose the country that applies to you.',
    history: 'Conversation history', conversation: 'Conversation', historyCopy: 'These transcripts are stored only on this device.', noHistory: 'No saved conversations.', messageCount: '{{count}} message{{plural}}', deleteConversation: 'Delete this conversation', deleteConversationTitle: 'Delete this conversation?', deleteConversationCopy: 'This transcript will be deleted only from this phone.', deleteAll: 'Delete all', deleteAllTitle: 'Delete all?', deleteAllCopy: 'All local transcripts will be deleted. This cannot be undone.', cancel: 'Cancel', delete: 'Delete',
    profile: 'My profile', conversations: 'My conversations', billing: 'Billing', signature: 'Made with ❤️ in Abidjan by Etudesk', saveProfile: 'Save profile', saving: 'Saving…', saveHistory: 'Keep my conversations', saveHistoryCopy: 'Off by default. When enabled, text is encrypted and stays only on this phone.', deletePassport: 'Delete passport', deleting: 'Deleting…', deletePassportTitle: 'Delete passport?', deletePassportCopy: 'Your profile, skills, credits, and transcripts will be deleted. This cannot be undone.', deleteUnavailable: 'Deletion unavailable', saveUnavailable: 'Unable to save', profileSaved: 'Profile saved',
    nameRequired: 'First name required', nameRequiredCopy: 'Enter the first name to display in your passport.', profileCreated: 'Passport created', profileCreatedCopy: 'Your profile is stored only on this device.', profileError: 'Profile', error: 'Error', unavailable: 'Unavailable',
  },
} as const;

export type TextKey = keyof typeof copy.fr;
export function t(locale: Locale, key: TextKey, values: Record<string, string | number> = {}) {
  return copy[locale][key].replace(/{{(\w+)}}/g, (_, name) => String(values[name] ?? ''));
}
export function plural(locale: Locale, value: number) { return locale === 'fr' ? (value === 1 ? '' : 's') : (value === 1 ? '' : 's'); }
export function dateLocale(locale: Locale) { return locale === 'en' ? 'en-US' : 'fr-FR'; }
